In [ ]:
# SECTION 1
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

In [ ]:
# SECTION 1

# Exercise 1 View the first five rows of the DataFrame.
df.head(5)

In [ ]:
# Exercise 1 View the first five rows of the DataFrame.
df.head(5)

In [ ]:
# Exercise 3 Get basic info about the DataFrame.
df.info()

In [ ]:
#Exercise 4 Check the shape of the DataFrame.
df.shape

In [ ]:
# SECTION 1
# Exercise Set 2: Indexing with .loc[] and .iloc[]

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head())

In [ ]:
# Exercise 1 Use .loc to get the name and age of the passenger with index 12.

print(df.loc[12, ['Name', 'Age']])

In [ ]:
# Exercise 2 Use .iloc to get the first 5 rows and first 3 columns.
df.iloc[0:5, 0:3]

In [ ]:
df.columns

In [ ]:
# Exercise 3 Use .loc to get all passengers in 1st class who are female.

df.loc[(df['Pclass']== 1) & (df['Sex']== 'female')]

In [ ]:
# Use .iloc to get the age of the 10th passenger (by position).
float(df.iloc[9]['Age'])

In [ ]:
# Exercise 5 Use .loc to get the Fare and Survived values for passengers with index 100 to 105.
df.loc[100:105,['Fare','Survived']]

In [ ]:
# SECTION 1
# Exercise Set 3: Summary Tools
# Use this starter code in your own environment:

import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

In [ ]:
# Exercise 1 Summarize the numeric columns.
df.describe()

In [ ]:
# Exercise 2 Use .value_counts() to see counts for embarkation ports.
df['Embarked'].value_counts()

In [ ]:
# Exercise 3 Use .value_counts() to count passenger classes.
df['Pclass'].value_counts()

In [ ]:
# Exercise 4 Show the average (mean) age of passengers.
float(df['Age'].mean())

In [ ]:
# Exercise 5 Show the maximum fare paid.
float(df['Fare'].max())

In [ ]:
# Exercise 6 Show how many unique names are in the dataset.
df['Name'].nunique()

In [ ]:
# Show counts for values in the Sex column.
df['Sex'].value_counts()

In [ ]:
# Exercise 8 Show how many unique values are in each column.
df.nunique()

In [ ]:
#SECTION2 Clean & Tidy Data
# Exercise Set 1: Dropping Data

In [26]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

In [ ]:
# Exercise 1 Drop the Email column and store the result in a new variable.
df_new = df.drop(columns=['Email'])
df_new

In [28]:
# Exercise 2 Drop the row with index 2 in place.
df.drop(index=2,inplace=True)
df

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

In [ ]:
# ***Exercise 3 Drop the City and Email columns, and assign the result back to df.

df=df.drop(columns=['City', 'Email'])
df

In [27]:
# Exercise 4 Drop the first and last row, and store the result in df_trimmed.

df_trimmed = df.drop(index=df.index[[0, -1]])
df_trimmed

      Name  Age     City          Email
1      Bob   30       LA  b@example.com
2  Charlie   35  Chicago  c@example.com

In [29]:
##Set 2 Exercise Set 2: Missing Data

import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

In [30]:
#Exercise 1 View the first 5 rows of the DataFrame.

df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0    None
3    David  40.0   Miami
4      Eva   NaN  Boston

In [31]:
#Exercise 2 Show where values are missing.

df.isnull()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [32]:
# Exercise 3 Count missing values by column.
df.isnull().sum()

Name    0
Age     2
City    1
dtype: int64

In [33]:
#Exercise 6 Drop columns with missing data.
print(df.dropna(axis=1))

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

In [34]:
#Exercise 8 Fill missing Age values with the mean.
mean_age = df['Age'].mean()
df['Age'] = df['Age'].fillna(mean_age)
df

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000    None
3    David  40.000000   Miami
4      Eva  33.333333  Boston

In [35]:
# Exercise 9 Fill missing City values with "Unknown".
df['City']=df['City'].fillna("Unknown")
df

      Name        Age     City
0    Alice  25.000000      NYC
1      Bob  33.333333       LA
2  Charlie  35.000000  Unknown
3    David  40.000000    Miami
4      Eva  33.333333   Boston

In [ ]:
# Exercise Set 3: Duplicates

In [36]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

In [37]:
# Exercise 1 Find which rows are duplicates across all columns.
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [38]:
#Exercise 2 Drop duplicate rows, keeping the first occurrence.

df.drop_duplicates()

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

In [39]:
# Exercise 3 Drop duplicate rows, keeping only the last occurrence.
df.drop_duplicates(keep='last')

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

In [40]:
#Exercise 4 Drop all duplicates, removing both the original and duplicate rows.
df_unique = df.drop_duplicates(keep=False)
print(df_unique)

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

In [ ]:
#Section 3: Data Wrangling Essentials
#Exercise Set 1: Renaming Columns

In [41]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

In [42]:
# Exercise 1 Change fname to FirstName and lname to LastName.
df.rename(columns={'fname': 'FirstName', 'lname': 'LastName'})

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [43]:
# Exercise 2 Change all column names to: ['FirstName', 'LastName', 'Country']
df.rename(columns={'fname': 'FirstName', 'lname': 'LastName','ctry': 'Country'})

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

In [44]:
# Exercise Set 2: Reordering Columns

import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

In [45]:
# Exercise 1 Rename Dept to Department and Sal to Salary.
df=df.rename(columns={"Dept":'Department', "Sal":'Salary'})
df

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

In [46]:
#Exercise 2 Reorder columns so Salary appears first, followed by Name and Department.
# Reorder columns
df = df[['Salary', 'Name', 'Department']]

In [47]:
# Exercise 3 Print the updated DataFrame.
print(df)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

In [ ]:
#Exercise Set 3: GroupBy and Aggregation

In [49]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

In [50]:
# Exercise 1 Group the data by Store and use .agg() to find the average Sales and average Profit for each store.
result = df.groupby('Store').agg(
    Avg_Sales=('Sales', 'mean'),
    Avg_Profit=('Profit', 'mean')
).reset_index()



print(result.to_string(index=False))

Store  Avg_Sales  Avg_Profit
    A      90.00       25.00
    B     115.00       37.50
    C      78.75       21.75

In [51]:
#Exercise 2 Group by Product and get the maximum Sales and minimum Profit.
result = df.groupby('Product').agg(
    Sales=('Sales', 'max'),
    Profit=('Profit', 'min')
).reset_index()

print(result.to_string(index=False))

Product  Sales  Profit
 Apples    120      30
Bananas    110      18
Oranges     80      15

In [52]:
#Exercise 3 Group by Store and return the average Sales and maximum Profit, but name the columns 
# Avg_Sales and Max_Profit.

result = df.groupby('Store').agg(
    Ave_Sales=('Sales', 'mean'),
    Max_Profit=('Profit', 'max')
).reset_index()

print(result.to_string(index=False))

Store  Ave_Sales  Max_Profit
    A      90.00          30
    B     115.00          40
    C      78.75          32

In [53]:
#Exercise 4 BONUS: Group by both Store and Product, and find the total Sales using .agg().
result = df.groupby(['Store','Product']).agg(
    Total_Sales=('Sales', 'sum')
    
).reset_index()
print(result.to_string(index=False))

Store Product  Total_Sales
    A  Apples          100
    A Bananas           90
    A Oranges           80
    B  Apples          120
    B Bananas          110
    C  Apples           95
    C Bananas          160
    C Oranges           60

In [54]:
# Exercise Set 4: Joining

import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

df_cities = pd.DataFrame({
    'City': ['NYC', 'LA', 'Chicago']
}, index=[101, 102, 103])

In [55]:
#Exercise 1 Join df_orders to df_customers on the index.
print(df_customers.join(df_orders))

    CustomerName  OrderTotal
101        Alice         250
102          Bob         300
103      Charlie         400

In [56]:
#Exercise 2 Add a new column to df_customers with city data from df_cities.

print(df_customers.join(df_cities))

    CustomerName     City
101        Alice      NYC
102          Bob       LA
103      Charlie  Chicago